<a href="https://colab.research.google.com/github/challengingJC/AIstudy/blob/main/2018732059_%EC%9D%B4%EC%A4%80%EC%B2%A0_assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor manipulation
### imports

In [ ]:
import numpy as np
import torch

# 1 Tensor in pytorch

# Rank, Shape, Axis
## Rank
- 열벡터에 의해 span된 벡터공간의 차원.

## Shape
- 각 Axis가 몇 개의 element를 가지고 있는지 나타내준다.

## Axis
- Axis of a tensor is a specific dimension of a tensor. 단, 세는 덩어리가 큰(하위 axis의 element가 많은) axis가 상위 axis이다.


In [ ]:
# Numpy와 비슷한 문법
tensor = torch.FloatTensor([1, 2, 3, 4])
print(tensor)
print(tensor.shape)
print(tensor[1:3])

tensor([1., 2., 3., 4.])
torch.Size([4])
tensor([2., 3.])


In [ ]:
# 3차원 이상
tensor3d = torch.FloatTensor([ [[1, 2, 3, 4], 
                                [5, 6, 7, 8],
                                [9, 10, 11, 12]],
                              
                               [[13, 14, 15, 16],
                                [17, 18, 19, 20],
                                [21, 22, 23, 24]] ])
print(tensor3d)
print(tensor3d.shape)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
torch.Size([2, 3, 4])


# 2 Tensor Combinations
- Concatenation
  - 경계를 무너뜨리며 붙인다

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(x)
print(y)
print(torch.cat([x,y], dim = 0))
print(torch.cat([x,y], dim = 1))
torch.cat([x,y], dim = 1).shape

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


torch.Size([2, 4])

- Stack  
  - 경계를 구분한 채로 붙인다

In [ ]:
print(torch.stack([x,y], dim = 0))
print(torch.stack([x,y], dim = 1))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])


- View / Reshape
  - data를 유지한 채 shape을 변형한다
    - Pointer를 반환하므로 원본을 훼손하지 않으려면 복사본을 이용한다
    - 반환된 tensor는 원본 tensor와 기반이 되는 data를 공유한다. 만약 반환된 tensor의 값이 변경된다면, viewed되는 tensor에서 해당하는 값이 변경된다. 
    - 원본 tensor의 복사본 혹은 view를 반환한다. 그러니 결국 copy를 받을지 view를 받을지 모른다. 만약 원본 input과 동일한 저장이 필요할 경우, clone()을 이용해서 copy하거나 view()를 이용해야한다고 한다.

In [ ]:
x = torch.rand(2, 3, 4)  # [2, 3, 4] 
y = x.view(2, -1)  # [2, 12] 
z = x.reshape(2, -1) # [2, 12]
print(x)
print(y)
print(z)
z[0] = 0.0
print(x)

tensor([[[0.0276, 0.3809, 0.3881, 0.9102],
         [0.0641, 0.7622, 0.6952, 0.4491],
         [0.0014, 0.1051, 0.4315, 0.9155]],

        [[0.9487, 0.6612, 0.3796, 0.5857],
         [0.6095, 0.2899, 0.1028, 0.2640],
         [0.1117, 0.7060, 0.8680, 0.7170]]])
tensor([[0.0276, 0.3809, 0.3881, 0.9102, 0.0641, 0.7622, 0.6952, 0.4491, 0.0014,
         0.1051, 0.4315, 0.9155],
        [0.9487, 0.6612, 0.3796, 0.5857, 0.6095, 0.2899, 0.1028, 0.2640, 0.1117,
         0.7060, 0.8680, 0.7170]])
tensor([[0.0276, 0.3809, 0.3881, 0.9102, 0.0641, 0.7622, 0.6952, 0.4491, 0.0014,
         0.1051, 0.4315, 0.9155],
        [0.9487, 0.6612, 0.3796, 0.5857, 0.6095, 0.2899, 0.1028, 0.2640, 0.1117,
         0.7060, 0.8680, 0.7170]])
tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.9487, 0.6612, 0.3796, 0.5857],
         [0.6095, 0.2899, 0.1028, 0.2640],
         [0.1117, 0.7060, 0.8680, 0.7170]]])


- Squeeze
  - 불필요한 rank를 줄인다

In [ ]:
_data = np.array([1,2,3,4])
x = torch.from_numpy(_data)
print(x)
print(x.T)
_data = np.array([_data])
x = torch.from_numpy(_data)
print(x)
print(x.T)
print(x.T.squeeze())

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])


# 3 Tensor Operations
## 사칙연산 - 요소별(Element-wise) 연산

In [ ]:
# 요소별 곱셈
print(tensor)
print(tensor3d)
print(tensor * tensor3d) #직관적으로 가능할 지 판단.

tensor([1., 2., 3., 4.])
tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 1.,  4.,  9., 16.],
         [ 5., 12., 21., 32.],
         [ 9., 20., 33., 48.]],

        [[13., 28., 45., 64.],
         [17., 36., 57., 80.],
         [21., 44., 69., 96.]]])


In [ ]:
tensor3d = torch.FloatTensor([ [[1, 2], 
                                [5, 6]
                                ],
                              
                              [[1, 2], 
                                [5, 6]],
                              
                              
                               [[13, 14],
                                [17, 18]] ])
tensor3d.shape
torch.stack([tensor3d,tensor3d,tensor3d], dim = 1).shape


torch.Size([3, 3, 2, 2])

In [ ]:
# 상수 덧셈
print(tensor3d + 3)

tensor([[[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.],
         [24., 25., 26., 27.]]])


In [ ]:
# tensor 덧셈
tensor_a = torch.FloatTensor([1, 2, 3, 4])
tensor_b = torch.FloatTensor([[1], [2], [3]])
tensor_c = torch.FloatTensor([[[1]],[[2]]])
print(tensor3d)
print(tensor3d + tensor_a)
print(tensor3d + tensor_b)
print(tensor3d + tensor_c)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 2.,  4.,  6.,  8.],
         [ 6.,  8., 10., 12.],
         [10., 12., 14., 16.]],

        [[14., 16., 18., 20.],
         [18., 20., 22., 24.],
         [22., 24., 26., 28.]]])
tensor([[[ 2.,  3.,  4.,  5.],
         [ 7.,  8.,  9., 10.],
         [12., 13., 14., 15.]],

        [[14., 15., 16., 17.],
         [19., 20., 21., 22.],
         [24., 25., 26., 27.]]])
tensor([[[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]],

        [[15., 16., 17., 18.],
         [19., 20., 21., 22.],
         [23., 24., 25., 26.]]])


- Tensor transpose
  - shape(2, 3, 4) >> shape(4, 3, 2)
  - 3차원의 경우, 머릿속으로 상상하기 힘들다

In [ ]:
print(tensor3d)
print(tensor3d.T)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],

        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],

        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]],

        [[ 4., 16.],
         [ 8., 20.],
         [12., 24.]]])


- Tensor dot product
  - 마찬가지로 3차원의 경우, 머릿속으로 상상하기 힘들기 때문에 수식에 오류가 없음을 반드시 확인해야한다
  - shape(2,3,4) * shape(4) >> shape(2,3)

In [ ]:
print(tensor3d.matmul(tensor))

tensor([[ 30.,  70., 110.],
        [150., 190., 230.]])


- Mean, Sum, Max

In [ ]:
print(tensor3d)
print(tensor3d.mean())
print(tensor3d.shape)
print(tensor3d.mean(dim=0))
print(tensor3d.mean(dim=1))
print(tensor3d.mean(dim=2))

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor(12.5000)
torch.Size([2, 3, 4])
tensor([[ 7.,  8.,  9., 10.],
        [11., 12., 13., 14.],
        [15., 16., 17., 18.]])
tensor([[ 5.,  6.,  7.,  8.],
        [17., 18., 19., 20.]])
tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])


In [ ]:
print(tensor3d.sum())
print(tensor3d.sum(dim=0))

tensor(300.)
tensor([[14., 16., 18., 20.],
        [22., 24., 26., 28.],
        [30., 32., 34., 36.]])


In [ ]:
print(tensor3d.max())
print(tensor3d.max(dim=1))
values, indices = tensor3d.max(dim=1)
print(values)

tensor(24.)
torch.return_types.max(
values=tensor([[ 9., 10., 11., 12.],
        [21., 22., 23., 24.]]),
indices=tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]]))
tensor([[ 9., 10., 11., 12.],
        [21., 22., 23., 24.]])


- 역행렬

In [ ]:
tensor_square = torch.FloatTensor([[1, 7], [-4, 6]])
print(torch.inverse(tensor_square))

tensor([[ 0.1765, -0.2059],
        [ 0.1176,  0.0294]])


In [ ]:
tensor_square.matmul(torch.inverse(tensor_square))
#행렬곱이 단위 행렬이 나오는 것으로 보아 torch.inverse가 제대로 역행렬을 구해주는 것을 알 수 있음.

tensor([[1., 0.],
        [0., 1.]])

In [ ]:
A = torch.FloatTensor([[0, 1], [1, 1], [2, 1], [3, 1]])

In [ ]:
print(torch.inverse(A))
# A는 역행렬 존재하지 않는다.

RuntimeError: ignored

실제 A의 역행렬이 존재하지 않아 x가 존재하지 않으나 오차 = Measured Value − True Value로 정의할 때 오차의 제곱을 최소화 하는 방법으로  
근사 해를 찾게되고 
여기서 사용되는 방법이 Pseudo Inverse Matrix입니다.  
역행렬대신 사용되는 의사역행렬은 다음과 같습니다.  
__A<SUP>+</SUP> = (A<SUP>T</SUP>A)<SUP>-1</SUP>A<SUP>T</SUP>__  

X = A<SUP>+</SUP>B 

In [ ]:
B = torch.FloatTensor([[-1],[0.2],[0.9],[2.1]])

In [ ]:
temp1 = A.T.matmul(A) # A전치행렬과 A의 행렬곱을 temp1에 저장합니다.
temp2 = torch.inverse(temp1) # temp1에 저장된 행렬의 역행렬을 구하고 그 행렬을 다시 temp2라 합니다.
P_I_A = temp2.matmul(A.T) # temp2와 A전치행렬의 행렬곱이 구하는 의사 역행렬입니다.

In [ ]:
X = P_I_A.matmul(B) # 의사역행렬과 B의 행렬곱이 구하는 근사해 입니다.

In [ ]:
print(X) #우리가 구하고자 하는 해를 출력해보았습니다.
A.matmul(X) #B와는 어느 정도 오차가 존재함을 확인하였습니다.

tensor([[ 1.0000],
        [-0.9500]])


tensor([[-0.9500],
        [ 0.0500],
        [ 1.0500],
        [ 2.0500]])